config/routes.rb
Rails.application.routes.draw do
  resources :cities

  resources :students
  
  resources :forecasts

 

  
  get '/auth/github/callback', to: 'session#create'
end

app/models/city.rb
class City < ActiveRecord::Base
  before_validation :geocode
	
  def weather 
		if self.lat
			ForecastIO.forecast(self.lat, self.lon).currently.icon
		else
			'unknown'
		end
	end
		
  public

  def forecast_io
    forecast = ForecastIO.forecast(self.lat, self.lon, params: { units: 'si' })
    results = {}
	  results[:temperature] = forecast.currently.temperature
    results[:summary] = forecast.currently.summary
    results[:windSpeed] = forecast.currently.windSpeed
	  results
  end

  def geocode
    places = Nominatim.search.city(self.name).limit(1)
    self.lat=places.first.lat
    self.lon=places.first.lon
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  def major?
    birthday < Time.now - 18.years
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
       	@cities.each do | city |
		        city.forecast_io
	  end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @forecasts = @city.forecast_io
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :lat, :lon)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
     puts request.env['omniauth.auth']
     render text: request.env['omniauth.auth'] .to_yaml
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :surname, :birthday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
  class_name = current_page?(link_path) ? 'active' : ''

  content_tag(:li, :class => class_name) do
    link_to link_text, link_path
  end
end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lat</th>
      <th>Lon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.lat %></td>
        <td><%= city.lon %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @city.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @city.lon %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @forecasts[:temperature] %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @forecasts[:summary] %>
</p>

<p>
  <strong>Windspeed:</strong>
  <%= @forecasts[:windSpeed] %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse ">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">LPA2</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <%= nav_link('students', students_path ) %>
            <%= nav_link('cities', cities_path ) %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<div class="form-group">
<%= render 'form' %>
</div>
<%= link_to('Show', @student, class: 'btn btn-primary btn-sm') %>
<%= link_to('Back', students_path, class: 'btn btn-primary btn-sm') %>

app/views/students/index.html.erb
<table class="table table-hover">
	<h1>Listing Students</h1>
   <thead>
      <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Birthday</th>
      </tr>
   </thead>
   <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.surname %></td>
        <td><%= student.birthday %></td>
				<td><%= link_to("Show", student, class: "btn btn-primary btn-sm") %></td>
        <td><%= link_to('Edit', edit_student_path(student), class: "btn btn-warning btn-sm") %></td>
        <td><%= link_to( 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm") %></td>
      </tr>
    <% end %>
   </tbody>
</table>
<a class='btn btn-success' href="students/new">New Student</a>

app/views/students/new.html.erb
<%= render 'form' %>

<a class='btn btn-primary' href="../students">Back</a>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p style="margin-bottom:20px;">
  <strong class="text-primary">Name:</strong>
  <%= @student.name %>
</p>

<p style="margin-bottom:20px;">
  <strong class="text-primary">Surname:</strong>
  <%= @student.surname %>
</p>

<p style="margin-bottom:20px;">
  <strong class="text-primary">Birthday:</strong>
  <%= @student.birthday %>
</p>

<p style="margin-bottom:20px;">
  <strong class="text-primary">major:</strong>
  <%= @student.major? %>
</p>

<td><%= link_to("Edit", edit_student_path(@student), class: "btn btn-warning btn-m") %></td>

<td><%= link_to("Back", students_path, class: "btn btn-primary btn-m") %></td>
				